### ISSUE TITLE
How to fuse the "SC-Rpresentations" into baseline model?

### ISSUE THREAD

**Issue by gaotianci99** [cocoon2wong/SocialCircle#3]
![image](https://github.com/cocoon2wong/SocialCircle/assets/126347638/10de6faa-16bd-497f-8457-9434d551835f)
![image](https://github.com/cocoon2wong/SocialCircle/assets/126347638/0cf6d461-6c32-40bf-9f0c-24c0252fcb9b)
Thanks for the authors nice works! I have a question, the final SCRpresentations with dimension(T_obs, 128) which contained both Temporal and Spatial Relations among ego-agent to neibor-agents. How to fuse it into baseline model? In the"socialcircle/v_sc.py", the forward() code can't see how to fuse it into v model.

**Comment by cocoon2wong** [comment]
Hi @17771618951 !

In the first one of your provided images, we have

```python
f_final = torch.concat([f_traj, f_z], dim=-1)
```

in the `v` model.

The SocialCircle Representation (`f_social`) is concatenated and encoded with the original trajectory representation `f_traj` as

```python
f_behavior = torch.concat([f_traj, f_sociall, dim=-1)
f_behavior = self.concat_fc(f_behavior)
```

Then, `f_behavior` takes the place of `f_traj`, thus making predictions.
In your provided `v_sc` image, we have:

```python
f_final = torch.concat([f_behavior, f_z], dim=-1)
```

I hope these might help you!

**Comment by gaotianci99** [comment]
I  got it, thanks for your answers!
