### ISSUE TITLE
Evaluation of ADE/FDE

### ISSUE THREAD

**Issue by hilbert9221** [cocoon2wong/SocialCircle#4]
Thank you for your wonderful code! I try to develop new methods based on your code. I am confused about the computation of ADE/FDE in two aspects:
1. As I expected, ADE is computed over all future steps, for example, 12 for ETH/UCY datasets. However, from the `args.json` and the code in `socialcircle`, it seems that the model only make predictions at the key points. Can you show me in what scenarios the code will make predictions for 12 steps?
2. Where are the final metrics of ADE/FDE stored? From the event log of tensorboard, it seems that only the FDE is reported.

Can you provide some explanation? Thanks in advance.

**Comment by cocoon2wong** [comment]
Hi @hilbert9221 !
Thanks for your questions!

In our paper, our backbone methods (`v`, `ev`, `msn`) all use the 2-stage prediction pipeline. Their first stage aims at forecasting trajectories on several keypoints, and the second stage uses interpolation methods to finish prediction. In socialCircle methods, our main work lies in representing social interactions in their first stage models, and we only use linear-speed interpolation to finish prediction. Thus, when training these models, only FDEs have been logged, and their ADEs (on the keypoints) are actually logged as the `avgKey` or `ADE(keypoints)` (in our Tensorflow or torch codes).

To obtain the entire prediction trajectories, please use
```
python main.py --sc SOME_MODEL_WEIGHTS
```
and you can see its ADE on all predicted frames, like
```
>>> [Train Manager]: Test Results
    - ADE(Metrics): 0.17835339903831482 (meter).
    - FDE(Metrics): 0.2975457012653351 (meter).
    - Average Inference Time: 357 ms.
    - Fastest Inference Time: 168 ms.

[INFO] `Train Manager` (SilverballersMKII): Test done. Split: zara1, load: null, metrics: {'ADE(Metrics)': '0.17835339903831482 (meter)', 'FDE(Metrics)': '0.2975457012653351 (meter)', 'Average Inference Time': '357 ms', 'Fastest Inference Time': '168 ms'}.
[INFO] `Train Manager` (SilverballersMKII): Test with subnetworks ['../Project-Monandaeg-SC/evsczara1', 'null'] done.
```

The alias `--sc` equals to
https://github.com/cocoon2wong/SocialCircle/blob/396fe658e21bbff1094fcc51fd59a1ec7d278afa/socialCircle/__init__.py#L21

On the contrary, if you just want to test these single-stage-one models, please use
```
python main.py --load SOME_MODEL_WEIGHTS
```
and the reported metrics are the avgKey and FDE:
```
>>> [Train Manager]: Test Results
    - ADE(keypoints)(Metrics): 0.23960411548614502 (meter).
    - FDE(keypoints)(Metrics): 0.2975548803806305 (meter).
    - Average Inference Time: 325 ms.
    - Fastest Inference Time: 165 ms.

[INFO] `Train Manager` (EVSCStructure): Test done. Split: zara1, load: ../Project-Monandaeg-SC/evsczara1, metrics: {'ADE(keypoints)(Metrics)': '0.23960411548614502 (meter)', 'FDE(keypoints)(Metrics)': '0.2975548803806305 (meter)', 'Average Inference Time': '325 ms', 'Fastest Inference Time': '165 ms'}.
```

(Please note their different class names, and the above results are obtained from our torch version of codes.)

I hope this helps!
Conghao Wong

**Comment by hilbert9221** [comment]
Thanks for you instant, elegant and comprehensive reply! Your explanation helps me understand the evaluation process of `SocialCircle` and its backbones `(v, ev, msn)`. I realize that the command `python main.py --sc SOME_MODEL_WEIGHTS` has appeared in the README. I have got similar results in the pytorch brunch. I can keep on with my projects now.
